game:
  grid_width: 10
  grid_height: 10
  wrap_around: true
  properties:
    initial_speed: 100
    speed_acceleration: 10
    min_speed: 40
  strategy: player

graphics:
  enable: false
  sizes:
    cell_size: 20
    margin: 50
  colors:
    background_color: [15, 15, 20]
    snake_color: [80, 220, 120]
    head_color: [120, 255, 160]
    food_color: [255, 90, 90]
    text_color: [235, 235, 235]
    grid_border_color: [40, 40, 60]
  font:
    font_name: "consolas"
    font_size: 28
    font_size_large: 48
  
