game:
  grid_width: 50
  grid_height: 50
  wrap_around: true
  properties:
    initial_speed: 10
    speed_acceleration: 10
    min_speed: 10
  strategy: hamiltonian_skip

hamiltonian:
  random_cycle: true

graphics:
  enable: true
  sizes:
    cell_size: 20
    margin: 50
  colors:
    background_color: [15, 15, 20]
    snake_color: [80, 220, 120]
    head_color: [120, 255, 160]
    food_color: [255, 90, 90]
    text_color: [235, 235, 235]
    grid_border_color: [40, 40, 60]
  font:
    font_name: "consolas"
    font_size: 28
    font_size_large: 48
